"""create country tables

Revision ID: d31e4121f75a
Revises: e6e492597bf2
Create Date: 2022-08-02 15:14:20.956670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31e4121f75a'
down_revision = 'e6e492597bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_alpha3', sa.String(length=3), nullable=False),
    sa.Column('alpha2', sa.String(length=2), nullable=True),
    sa.Column('zone', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('country_alpha3')
    )
    op.create_table('user_country',
    sa.Column('user_country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country_alpha3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_alpha3'], ['countries.country_alpha3'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_country_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_country')
    op.drop_table('countries')
    # ### end Alembic commands ###
